CREATE TABLE OAC.DEVICE_GROUP  ( 
	DG_ID      	NUMBER NOT NULL,
	NAME       	VARCHAR2(128) NOT NULL,
	MODEL_NAME 	VARCHAR2(50) NOT NULL,
	GSM_MODULE 	CHAR(1) NOT NULL,
	TEST_TYPE  	VARCHAR2(128) NULL,
	MOBILE_TYPE	NUMBER NULL,
	VENDER     	VARCHAR2(30) NULL,
	PATH       	VARCHAR2(128) NOT NULL,
	MEMORY_SIZE	NUMBER NULL,
	DEL_YN     	CHAR(1) DEFAULT 'N' NULL,
	CRT_DATE   	TIMESTAMP(6) NOT NULL,
	MDF_DATE   	TIMESTAMP(6) NULL 
	)
GO
INSERT INTO OAC.DEVICE_GROUP(DG_ID, NAME, MODEL_NAME, GSM_MODULE, TEST_TYPE, MOBILE_TYPE, VENDER, PATH, MEMORY_SIZE, DEL_YN, CRT_DATE, MDF_DATE)
  VALUES(47, 'Server', 'AIMIR', '2', 'AIMIR', NULL, NULL, 'AIMIR', NULL, 'N', TO_TIMESTAMP('2018-06-05 11:04:09:0','YYYY-MM-DD HH24:MI:SS:FF'), NULL)
GO
INSERT INTO OAC.DEVICE_GROUP(DG_ID, NAME, MODEL_NAME, GSM_MODULE, TEST_TYPE, MOBILE_TYPE, VENDER, PATH, MEMORY_SIZE, DEL_YN, CRT_DATE, MDF_DATE)
  VALUES(48, 'MBB_TEST', 'MBB_TEST', '2', 'MBB_TEST', NULL, NULL, 'MBB_TEST', NULL, 'N', TO_TIMESTAMP('2018-06-05 18:20:47:0','YYYY-MM-DD HH24:MI:SS:FF'), NULL)
GO
INSERT INTO OAC.DEVICE_GROUP(DG_ID, NAME, MODEL_NAME, GSM_MODULE, TEST_TYPE, MOBILE_TYPE, VENDER, PATH, MEMORY_SIZE, DEL_YN, CRT_DATE, MDF_DATE)
  VALUES(67, 'RF_MODEM_TEST', 'P20CSR', '2', 'P20CSR', NULL, NULL, 'aa', NULL, 'N', TO_TIMESTAMP('2018-06-08 11:10:11:0','YYYY-MM-DD HH24:MI:SS:FF'), NULL)
GO
INSERT INTO OAC.DEVICE_GROUP(DG_ID, NAME, MODEL_NAME, GSM_MODULE, TEST_TYPE, MOBILE_TYPE, VENDER, PATH, MEMORY_SIZE, DEL_YN, CRT_DATE, MDF_DATE)
  VALUES(68, 'GHANA_DCU_TEST', 'NDC-I531', '2', 'NDC-I531', NULL, NULL, 'GHANA_DCU_TEST', NULL, 'N', TO_TIMESTAMP('2018-06-08 11:35:33:0','YYYY-MM-DD HH24:MI:SS:FF'), NULL)
GO
INSERT INTO OAC.DEVICE_GROUP(DG_ID, NAME, MODEL_NAME, GSM_MODULE, TEST_TYPE, MOBILE_TYPE, VENDER, PATH, MEMORY_SIZE, DEL_YN, CRT_DATE, MDF_DATE)
  VALUES(69, 'GHANA_PDT', 'NAMR_P20CSR', '2', 'NAMR_P20CSR', NULL, NULL, 'aa', NULL, 'N', TO_TIMESTAMP('2018-06-08 12:02:35:0','YYYY-MM-DD HH24:MI:SS:FF'), NULL)
GO
INSERT INTO OAC.DEVICE_GROUP(DG_ID, NAME, MODEL_NAME, GSM_MODULE, TEST_TYPE, MOBILE_TYPE, VENDER, PATH, MEMORY_SIZE, DEL_YN, CRT_DATE, MDF_DATE)
  VALUES(27, 'AHOPE_TEST', 'TEST', '2', 'TEST', NULL, NULL, '1', NULL, 'N', TO_TIMESTAMP('2018-05-28 16:08:56:0','YYYY-MM-DD HH24:MI:SS:FF'), NULL)
GO
