CREATE TABLE OAC.METER_TERMINAL  ( 
	M_NUMBER             	VARCHAR2(50) NOT NULL,
	MASTER_KEY           	VARCHAR2(250) NULL,
	GLOBAL_KEY           	VARCHAR2(250) NULL,
	UNICAST_KEY          	VARCHAR2(250) NULL,
	LLS_SECRET_KEY       	VARCHAR2(250) NULL,
	HLS_SECRET_GLOBAL_KEY	VARCHAR2(250) NULL,
	HLS_SECRET_UNIQUE_KEY	VARCHAR2(250) NULL,
	AUTHENTICATION_KEY   	VARCHAR2(250) NULL,
	MDF_DATE             	TIMESTAMP(6) NULL,
	CRT_DATE             	TIMESTAMP(6) NOT NULL 
	)
GO
